Kheirie/Kheirie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Kheirie import settings
from Kheirie_Main.views import change_lang
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('change_lang', change_lang, name="change_lang")
]   

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', include('Kheirie_Main.urls')),

)


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Kheirie/Kheirie_Main/urls.py
from django.urls import path
from django.views.static import serve
from django.conf.urls import url
from Kheirie import settings
from .views import header, footer, home_page, DetailPage, PostList, category_page, about_us, contact_us


app_name = 'kheirie'
urlpatterns = [
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('', home_page, name='home'),
    path("detail/<slug:slug>/", DetailPage.as_view(), name="detail"),
    path("all-posts/", PostList.as_view(), name="all-posts"),
    path('category/<slug:slug>', category_page, name="category"),
    path('about-us', about_us, name="about-us"),
    path('contact-us', contact_us, name="contact-us"),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

Kheirie/Kheirie_Account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

Kheirie/Kheirie_Main/models.py
from django.db import models
from django.utils.html import format_html
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from translated_fields import TranslatedField
from django.utils.translation import gettext_lazy as _



class PostManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class Category(MPTTModel):
    parent = TreeForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name="children", verbose_name=_("زیر مجموعه"))
    title = TranslatedField(models.CharField(_("تیتر دسته بندی"), max_length=100, help_text="کادر اول فارسی کادر دوم انگلیسی"))
    slug = models.SlugField(_("نام دسته بندی در لینک(اسلاگ)"), max_length=100)
    status = models.BooleanField(_("وضعیت"), default=True)
    # Post Models
    title_post = TranslatedField(models.CharField(_("تیتر مقاله"), max_length=200, help_text = "کادر اول فارسی کادر دوم انگلیسی", blank=True))
    desc_post =  TranslatedField(RichTextUploadingField(_("توضیحات مقاله"), help_text = "کادر اول فارسی کادر دوم انگلیسی", blank=True))
    img_post = models.ImageField(_("عکس"), upload_to='media', blank=True, null=True)
    video_post = models.URLField(_("لینک کد امبد آپارات"), max_length=500, blank=True, null=True)
    download = models.FileField(_("آپلود فایل"), upload_to="documents" ,blank=True, null=True)



    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("دسته بندی")
        verbose_name_plural = _("دسته بندی ها")
        ordering = ['-id']



    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::1])



class Post(models.Model):
    STATUS = (
        ('p', 'Publish'),
        ('d', 'Draft'),
    )

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE, related_name="articles", verbose_name=_("دسته بندی"))
    title = TranslatedField(models.CharField(_("تیتر مقاله"), max_length=200, help_text="کادر اول فارسی کادر دوم انگلیسی"))
    slug = models.SlugField(_("نام مقاله در لینک (اسلاگ)"), )
    desc =  TranslatedField(RichTextUploadingField(_("توضیحات مقاله"), help_text="کادر اول فارسی کادر دوم انگلیسی"))
    img = models.ImageField(_("عکس"), upload_to='media', blank=True, null=True)
    video = models.URLField(_("لینک کد امبد آپارات"), max_length=500, blank=True, null=True)
    status = models.CharField(_("وضعیت"), max_length=1, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name = _("مقاله")
        verbose_name_plural = _("مقالات")
        ordering = ['-id']
        


    def __str__(self):
        return self.title


    def img_tag(self):
        return format_html('<img src="{}" width=100px />'.format(self.img.url))
    img_tag.short_description = "Image"

    objects = PostManager()

Kheirie/Kheirie_Panel/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from translated_fields import TranslatedField
from django.utils.translation import gettext_lazy as _



class Settings(models.Model):
    logo = TranslatedField(models.CharField(_("نام سایت"), max_length=100, blank=True, help_text="کادر اول فارسی کادر دوم انگلیسی"))
    address = TranslatedField(models.CharField(_("آدرس بنیاد"), max_length=300, blank=True, help_text="کادر اول فارسی کادر دوم انگلیسی"))
    phone_number = models.CharField(_("شماره تماس"), max_length=20, blank=True)
    phone_number2 = models.CharField(_("شماره تماس 2"), max_length=20, blank=True)
    email = models.CharField(_("ایمیل"), max_length=50, blank=True)
    description_footer = TranslatedField(models.CharField(_("توضیحات فوتر"), max_length=300, blank=True, help_text="کادر اول فارسی کادر دوم انگلیسی"))
    instagram = models.URLField(_("اینستاگرام"), blank=True)
    telegram = models.URLField(_("تلگرام"), blank=True)
    whatsapp = models.URLField(_("واتساپ"), blank=True)
    linkdin = models.URLField(_("لینکدین"), blank=True)
    about_company = TranslatedField(RichTextUploadingField(_("درباره بنیاد"), help_text="کادر اول فارسی کادر دوم انگلیسی"))

    def __str__(self):
        return self.logo

    class Meta:
        verbose_name = _("تنضیمات")
        verbose_name_plural = _("تنظیمات")
    

Kheirie/Kheirie_Account/views.py
from django.shortcuts import render

# Create your views here.

Kheirie/Kheirie_Main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from .models import Post, Category
from Kheirie_Panel.models import Settings
from django.utils.translation import activate


# Header Code Behind

def header(request):
    settings = get_object_or_404(Settings)
    category = Category.objects.filter(status=True)
    context = {
        'settings' : settings,
        'category' : category,
    }
    return render(request, 'shared/Header.html', context)


# Footer Code Behind

def footer(request):
    settings = get_object_or_404(Settings)
    category = Category.objects.filter(status=True)
    context = {
        'settings' : settings,
        'category' : category,

    }
    return render(request, 'shared/Footer.html', context)


def home_page(request):
    post = Post.objects.published().order_by('-id')[:9]
    category = Category.objects.filter(status=True)
    settings = get_object_or_404(Settings)
    context = {
        'object_list': post,
        'settings' : settings,
        'category': category
    }
    return render(request, 'home_page.html', context)



class DetailPage(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Post.objects.published(), slug=slug)

    template_name = 'detail_page.html'


class PostList(ListView):
    queryset = Post.objects.published().order_by('-id')
    template_name = 'post_list.html'


def category_page(request, slug):
    category = get_object_or_404(Category, slug=slug)
    context = {
        'cat': category,
    }
    return render(request, 'category_page.html', context)


def about_us(request):
    settings = get_object_or_404(Settings)
    context = {
        'settings' : settings,
    }
    return render(request, 'about_us.html', context)


def contact_us(request):
    settings = get_object_or_404(Settings)
    context = {
        'settings' : settings,
    }
    return render(request, 'contact_us.html', context)


def change_lang(request):
    activate(request.GET.get('lang'))
    return redirect(request.GET.get('next'))

Kheirie/Kheirie_Panel/views.py
from django.shortcuts import render

# Create your views here.

Kheirie/templates/home_page.html
 {% extends 'shared/Main_Layout.html' %}
 {% load static %}
 {% load i18n %}
 {% block content %}

		<section class ="owl-curve-green">
            <div class="gap no-gap">
                <img class="botm-shp shp-img" src="{% static 'assets/images/shp2-1.png' %}" alt="shp2-1.png">
                <div class="featured-area-wrap text-center">
                    <div class="featured-area2 owl-carousel">
                    {% for ps in object_list %}
                        <div class="featured-item style2" style="background-image: url({% static 'assets/images/pira.jpg' %});">
                            <div class="featured-cap">
                                <h3>{{ps.title}}</h3>
                                <span style='direction: rtl'>{{ps.desc|truncatewords:15|striptags}}</span>
                                <a class="thm-btn brd-rd5" href="{% url 'kheirie:detail' ps.slug %}" title="">{% translate 'بیشتر بخوانید' %}<i class="flaticon-left-arrow"></i></a>
                            </div>
                        </div>
                    {% endfor %}    
                    </div>
                </div><!-- Featured Area Wrap -->
            </div>
        </section>
        
        <section>
            <div class="gap">
                <div class="container">
                    <div class="hstry-wrap">
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-lg-6">
                                <div class="hstry-img text-center">
                                    <img src="{% static 'assets/images/resources/hstry-img.png' %}" alt="hstry-img.png">
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12 col-lg-6">
                                <div class="hstry-desc">
                                    {{settings.about_company|safe}}
                                </div>
                            </div>
                        </div>
                    </div><!-- History Wrap -->
                </div>
            </div>
        </section>
        
        <section>
            <div class="gap">
                <div class="container">
                    <div class="event-wrap">
                        <div class="row">

                            <div class="col-md-12 col-sm-12 col-lg-12">
                                <div class="remove-ext3">
                                    <div class="row">
										{% for rs in object_list %}
                                                <div class="col-md-4 col-sm-4 col-lg-4">
                                                    <div class="event-box2">
                                                        <div class="event-thumb">
                                                            <a href="{% url 'kheirie:detail' rs.slug %}" title="">
                                                                {% if rs.img %}
                                                                    <img src="{{ rs.img.url }}" alt="event-img2-1.jpg" style="height:200px">
                                                                {% endif %}
                                                                {% if rs.video %}
                                                                <style>
                                                                    .h_iframe-aparat_embed_frame{position:relative;}.h_iframe-aparat_embed_frame .ratio{display:block;width:100%;height:auto;}.h_iframe-aparat_embed_frame iframe{position:absolute;top:0;left:0;width:100%;height:100%;}
                                                                </style>
                                                                <div class="h_iframe-aparat_embed_frame">
                                                                    <span style="display: block;padding-top: 57%"></span>
                                                                    <iframe src="{{ rs.video }}"></iframe>
                                                                </div>
                                                                {% endif %}
                                                            </a>
                                                        </div>
                                                        <div class="event-info">
                                                            <h4><a href="{% url 'kheirie:detail' rs.slug %}" title="">{{ rs.title|truncatewords:7 }}</a></h4>
                                                            <p>{{ rs.desc|truncatewords:30|safe }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                        {% endfor %}
                                    </div>
                                    <div class="view-all text-center">
                                        <a class="thm-btn brd-rd5" href="{% url 'kheirie:all-posts' %}" title="">{% trans "پست های بیشتر" %}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Event Wrap -->
                </div>
            </div>
        </section>

        <section>
            <div class="gap">
                <div class="container">
                    <div class="sec-title2 text-center">
                        <div class="sec-title-inner2">
                            <span>{% trans "خدمات بشر دوستانه" %}</span>
                            <h3>{% trans "خدمات ما" %}</h3>
                        </div>
                    </div>
                    <div class="serv-wrap text-center remove-ext3">
                        <div class="row">
                            <div class="col-md-3 col-sm-6 col-lg-3">
                                <div class="srv-box2">
                                    <i class="flaticon-quran-rehal"></i>
                                    <div class="srv-info2">
                                        <h4>آموزش قرآن</h4>
                                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6 col-lg-3">
                                <div class="srv-box2">
                                    <i class="flaticon-heart-1"></i>
                                    <div class="srv-info2">
                                        <h4>خدمات خیریه و کمک</h4>
                                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6 col-lg-3">
                                <div class="srv-box2">
                                    <i class="flaticon-mosque"></i>
                                    <div class="srv-info2">
                                        <h4>ساخت مساجد</h4>
                                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6 col-lg-3">
                                <div class="srv-box2">
                                    <i class="flaticon-social-care"></i>
                                    <div class="srv-info2">
                                        <h4>کمک به فقرا</h4>
                                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Serv Wrap -->
                </div>
            </div>
        </section>
        
        
        
{% endblock content %}

Kheirie/templates/post_list.html
{% extends 'shared/Main_Layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}

        <section>
            <div class="gap remove-bottom black-layer2 opc85">
                <div class="fixed-bg" style="background-image: url({% static "assets/images/pira.jpg" %});"></div>
                <div class="container">
                    <div class="page-title-wrap">
                        <h2>{% trans "رویداد ها و اطلاع رسانی ها" %}</h2>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="gap">
                <div class="container">
                    <div class="event-wrap">
                        <div class="row">
                            
                            <div class="col-md-12 col-sm-12 col-lg-12">
                                <div class="remove-ext3">
                                    <div class="row">
                                        {% for posts in object_list %}
                                            <div class="col-md-4 col-sm-6 col-lg-4">
                                                <div class="event-box2">
                                                    <div class="event-thumb">
                                                        <a href="{% url "kheirie:detail" posts.slug %}" title="">
                                                            {% if posts.img %}
                                                                    <img src="{{ posts.img.url }}" alt="event-img2-1.jpg" style="height:200px">
                                                            {% endif %}
                                                            {% if posts.video %}
                                                            <style>
                                                                    .h_iframe-aparat_embed_frame{position:relative;}.h_iframe-aparat_embed_frame .ratio{display:block;width:100%;height:auto;}.h_iframe-aparat_embed_frame iframe{position:absolute;top:0;left:0;width:100%;height:100%;}
                                                            </style>
                                                            <div class="h_iframe-aparat_embed_frame">
                                                                <span style="display: block;padding-top: 57%"></span>
                                                                <iframe src="{{ posts.video }}"></iframe>
                                                            </div>
                                                            {% endif %}
                                                        </a>
                                                    </div>
                                                    <div class="event-info">
                                                        <h4><a href="{% url "kheirie:detail" posts.slug %}" title="">{{ posts.title|truncatewords:7 }}</a></h4>
                                                        <p>{{ posts.desc|truncatewords:30|safe }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Event Wrap -->
                </div>
            </div>
        </section>

{% endblock content %}

{% for cat in category %}
                                {% if cat.parent == None %}
                                    <li class="menu-item-has-children"><a  href="{% url 'kheirie:category' cat.slug %}"  title="">{{cat.title}}</a> 
                                {% endif %}
                                {% if cat.children.all %}
                                    <ul>
                                    {% for cat in cat.children.all %}
                                        <li><a href="{% url 'kheirie:category' cat.slug %}" title="">{{cat.title}}</a></li>
                                    {% endfor %}
                                    </ul>    
                                {% endif %}
                                </li>
							{% endfor %}

Kheirie/templates/shared/Footer.html
{% load mptt_tags %}
{% load i18n %}



        <footer>
            <div class="gap top-spac70 drk-bg2 remove-bottom">
                <div class="container">
                    <div class="footer-data">
                        <div class="row">
                            <div class="col-md-4 col-sm-12 col-lg-4">
                                <div class="wdgt-box style2">
                                    <p>{{settings.description_footer}}</p>
                                </div>
                            </div>
                            <div class="col-md-8 col-sm-12 col-lg-8">
                                <div class="row">
                                    <div class="col-md-4 col-sm-4 col-lg-4">
                                        <div class="wdgt-box">
                                            <h4>{% trans "لینک های مفید" %}</h4>
                                            <ul>
                                                <li><a href="index-2.html#" title="">{% trans "خانه" %}</a></li>
                                                <li><a href="index-2.html#" title="">{% trans "اخبار" %}</a></li>
                                                {% recursetree category %}

                                                {% if node.is_leaf_node %}
                                                    <li class=""><a  href="{% url 'kheirie:category' node.slug %}"  title="">{{node.title}}</a> 
                                                {% endif %}


                                                {% endrecursetree %}
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-lg-4">
                                        <div class="wdgt-box">
                                            <h4>{% trans "صفحات سایت" %}</h4>
                                            <ul>
                                                <li><a href="{% url 'kheirie:home' %}" title="">{% trans "خانه" %}</a></li>
                                                <li><a href="{% url 'kheirie:all-posts' %}" title="">{% trans "اخبار" %}</a></li>
                                                {% recursetree category %}

                                                {% if node.is_leaf_node %}
                                                    <li class=""><a  href="{% url 'kheirie:category' node.slug %}"  title="">{{node.title}}</a> 
                                                {% endif %}


                                                {% endrecursetree %}
                                                <li><a href="{% url 'kheirie:contact-us' %}" title="">{% trans "تماس با ما" %}</a></li>
                                                <li><a href="{% url 'kheirie:about-us' %}" title="">{% trans "درباره ما" %}</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-lg-4">
                                        <div class="wdgt-box">
                                            <h4>{% trans "تماس با ما" %}</h4>
                                            <ul class="cont-lst">
                                                <li><i class="flaticon-location-pin"></i>{{settings.address}}</li>
                                                <li><i class="flaticon-call"></i>{{settings.phone_number}}</li>
                                                <li><i class="flaticon-email"></i><a href="index-2.html#" title="">{{settings.email}}</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Footer Data -->
                    <div class="bottom-bar">
                        <p>{% trans "1400 | تمامی حقوق برای جامعه محفوظ میباشد" %}</p>
                        <div class="scl">
                            <a href="{{settings.linkdin}}" title="توییتر" target="_blank"><i class="fa fa-linkedin"></i></a>
                            <a href="{{settings.instagram}}" title="اینستاگرام" target="_blank"><i class="fa fa-instagram"></i></a>
                            <a href="{{settings.whatsapp}}" title="گوگل پلاس" target="_blank"><i class="fa fa-whatsapp"></i></a>
                            <a href="{{settings.telegram}}" title="فیسبوک" target="_blank"><i class="fa fa-telegram"></i></a>
                        </div>
                    </div><!-- Bottom Bar -->
                </div>
            </div>
        </footer>

Kheirie/templates/shared/Footer_Refrences.html
{% load static %}

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/downCount.js' %}"></script>
    <script src="{% static 'assets/js/fancybox.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/perfectscrollbar.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.circliful.min.js' %}"></script>
    <script src="{% static 'assets/js/google-map-int.js' %}"></script>
    <script src="{% static 'assets/js/custom-scripts.js' %}"></script>

Kheirie/templates/shared/Header.html
{% load static %}
{% load mptt_tags %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}


        
        
        <header class="style2">
            <div class="container ">
                <div class="logo sec-title-inner2"><h3><a href="{% url 'kheirie:home' %}"><img src="{% static 'assets/images/logok.png' %}" style="width:170px"/></a></h3></div>
                <nav class="">
                    <div>
                    <a class="thm-btn brd-rd5" href="{% url 'kheirie:contact-us' %}" title="">{% trans "تماس با ما" %}</a>
                        <ul>
                            <li><a href="{% url 'kheirie:home' %}">{% trans "خانه" %}</a></li>
                            <li><a href="{% url 'kheirie:all-posts' %}">{% trans "اخبار" %}</a></li>
                            {% recursetree category %}
                                {% if node.is_leaf_node %}
                                    <li class=""><a  href="{% url 'kheirie:category' node.slug %}"  title="">{{node.title}}</a> 
                                {% else %}                                
                                    <li class="menu-item-has-children"><a  href=""  title="">{{node.title}}</a> 
                                {% endif %}
                                {% if not node.is_leaf_node %}
                                    <ul>
                                        <li><a href="{% url 'kheirie:category' node.slug %}" title="">{{children}}</a></li>
                                    </ul>    
                                {% endif %}
                                </li>
							{% endrecursetree %}

                            <li><a href="{% url 'kheirie:about-us' %}">{% trans "درباره ما" %}</a></li>
                            <li>
                            {% if LANGUAGE_CODE == 'en' %}
                                <a href="{% url 'change_lang' %}?lang=fa&next=/fa">فارسی</a>
                            {% endif %}
                            {% if LANGUAGE_CODE == 'fa' %}
                                <a href="{% url 'change_lang' %}?lang=en&next=/en">EN</a>
                            {% endif %}
                            </li>
                            
                            <li></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </header><!-- Header -->
        <div class="rspn-hdr">
            <div class="rspn-mdbr">
            </div>
            <div class="lg-mn">
                <div class="logo sec-title-inner2"><h3><a href="{% url 'kheirie:home' %}"><img src="{% static 'assets/images/logok.png' %}" style="width:100px" /></a></h3></div>
                <div class="rspn-cnt">
                    <span><i class="fa fa-envelope thm-clr"></i><a href="index-2.html#" title=""> {{settings.email}} </a></span>
                    <span><i class="fa fa-phone thm-clr"></i> {{settings.phone_number}} </span>
                </div>
                <span class="rspn-mnu-btn"> <i class="fa fa-list-ul"></i> </span>
            </div>
            <div class="rsnp-mnu">
                <span class="rspn-mnu-cls"> <i class="fa fa-times"></i> </span>
                <ul>
                    <li><a href="{% url 'kheirie:home' %}">{% trans "خانه" %}</a></li>
                    <li><a href="{% url 'kheirie:all-posts' %}">{% trans "اخبار" %}</a></li>
                    {% recursetree category %}
                        {% if node.is_leaf_node %}
                            <li class=""><a  href="{% url 'kheirie:category' node.slug %}"  title="">{{node.title}}</a> 
                        {% else %}                                
                            <li class="menu-item-has-children"><a  href=""  title="">{{node.title}}</a> 
                        {% endif %}
                        {% if not node.is_leaf_node %}
                            <ul>
                                <li><a href="{% url 'kheirie:category' node.slug %}" title="">{{children}}</a></li>
                            </ul>    
                        {% endif %}
                            </li>
					{% endrecursetree %}
                    <li><a href="{% url 'kheirie:about-us' %}">{% trans "درباره ما" %}</a></li>
                    <li><a href="{% url 'kheirie:contact-us' %}">{% trans "تماس با ما" %}</a></li>
                </ul>
            </div><!-- Responsive Menu -->
        </div><!-- Responsive Header -->


        <style>
        
        .lg-mn {background-color: white;}
        .lg-mn span {color:black;}

        </style>